#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-tomlkit
Version  : 0.10.2
Release  : 16
URL      : https://files.pythonhosted.org/packages/8b/95/c8826c61bd59c0d991fb1ca3d187d7fa803af13c1704be932e1071e041da/tomlkit-0.10.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/8b/95/c8826c61bd59c0d991fb1ca3d187d7fa803af13c1704be932e1071e041da/tomlkit-0.10.2.tar.gz
Summary  : Style preserving TOML library
Group    : Development/Tools
License  : ISC MIT
Requires: pypi-tomlkit-license = %{version}-%{release}
Requires: pypi-tomlkit-python = %{version}-%{release}
Requires: pypi-tomlkit-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
[github_release]: https://img.shields.io/github/release/sdispater/tomlkit.svg?logo=github&logoColor=white
[pypi_version]: https://img.shields.io/pypi/v/tomlkit.svg?logo=python&logoColor=white
[python_versions]: https://img.shields.io/pypi/pyversions/tomlkit.svg?logo=python&logoColor=white
[github_license]: https://img.shields.io/github/license/sdispater/tomlkit.svg?logo=github&logoColor=white
[github_action]: https://github.com/sdispater/tomlkit/actions/workflows/tests.yml/badge.svg

%package license
Summary: license components for the pypi-tomlkit package.
Group: Default

%description license
license components for the pypi-tomlkit package.


%package python
Summary: python components for the pypi-tomlkit package.
Group: Default
Requires: pypi-tomlkit-python3 = %{version}-%{release}

%description python
python components for the pypi-tomlkit package.


%package python3
Summary: python3 components for the pypi-tomlkit package.
Group: Default
Requires: python3-core
Provides: pypi(tomlkit)

%description python3
python3 components for the pypi-tomlkit package.


%prep
%setup -q -n tomlkit-0.10.2
cd %{_builddir}/tomlkit-0.10.2
pushd ..
cp -a tomlkit-0.10.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1653010649
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-tomlkit
cp %{_builddir}/tomlkit-0.10.2/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tomlkit/84661790a5df00ab944c2d37978d6ce5ac88e554
cp %{_builddir}/tomlkit-0.10.2/tests/toml-spec-tests/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tomlkit/7ad2173ba59937a324cdfe33686e42e2f29ee6ae
cp %{_builddir}/tomlkit-0.10.2/tests/toml-test/COPYING %{buildroot}/usr/share/package-licenses/pypi-tomlkit/7a82386b25eb7b8b4fbfd8427349ad9cdddf026d
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
## install_append content
rm -rf %{buildroot}/usr/lib/python3*/site-packages/tests
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-tomlkit/7a82386b25eb7b8b4fbfd8427349ad9cdddf026d
/usr/share/package-licenses/pypi-tomlkit/7ad2173ba59937a324cdfe33686e42e2f29ee6ae
/usr/share/package-licenses/pypi-tomlkit/84661790a5df00ab944c2d37978d6ce5ac88e554

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
